#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicaCC.DB
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="LXCC")]
	public partial class DBLXCCDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertEstado(Estado instance);
    partial void UpdateEstado(Estado instance);
    partial void DeleteEstado(Estado instance);
    partial void InsertServicioStatus(ServicioStatus instance);
    partial void UpdateServicioStatus(ServicioStatus instance);
    partial void DeleteServicioStatus(ServicioStatus instance);
    partial void InsertServicioTipo(ServicioTipo instance);
    partial void UpdateServicioTipo(ServicioTipo instance);
    partial void DeleteServicioTipo(ServicioTipo instance);
    partial void InsertDeclaracionEstado(DeclaracionEstado instance);
    partial void UpdateDeclaracionEstado(DeclaracionEstado instance);
    partial void DeleteDeclaracionEstado(DeclaracionEstado instance);
    partial void InsertPeriodo(Periodo instance);
    partial void UpdatePeriodo(Periodo instance);
    partial void DeletePeriodo(Periodo instance);
    partial void InsertDeclaracionTipo(DeclaracionTipo instance);
    partial void UpdateDeclaracionTipo(DeclaracionTipo instance);
    partial void DeleteDeclaracionTipo(DeclaracionTipo instance);
    #endregion
		
		public DBLXCCDataContext() : 
				base(global::LogicaCC.Properties.Settings.Default.LXCCConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBLXCCDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBLXCCDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBLXCCDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBLXCCDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Estado> Estado
		{
			get
			{
				return this.GetTable<Estado>();
			}
		}
		
		public System.Data.Linq.Table<ServicioStatus> ServicioStatus
		{
			get
			{
				return this.GetTable<ServicioStatus>();
			}
		}
		
		public System.Data.Linq.Table<ServicioTipo> ServicioTipo
		{
			get
			{
				return this.GetTable<ServicioTipo>();
			}
		}
		
		public System.Data.Linq.Table<DeclaracionEstado> DeclaracionEstado
		{
			get
			{
				return this.GetTable<DeclaracionEstado>();
			}
		}
		
		public System.Data.Linq.Table<Periodo> Periodo
		{
			get
			{
				return this.GetTable<Periodo>();
			}
		}
		
		public System.Data.Linq.Table<DeclaracionTipo> DeclaracionTipo
		{
			get
			{
				return this.GetTable<DeclaracionTipo>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.LXCCSPS_VALIDAR_USUARIO")]
		public ISingleResult<LXCCSPS_VALIDAR_USUARIOResult> LXCCSPS_VALIDAR_USUARIO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="User", DbType="NVarChar(45)")] string user, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password", DbType="NVarChar(45)")] string password)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), user, password);
			return ((ISingleResult<LXCCSPS_VALIDAR_USUARIOResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.LXCCSPS_LISTA_USUARIOS")]
		public ISingleResult<LXCCSPS_LISTA_USUARIOSResult> LXCCSPS_LISTA_USUARIOS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuarioTipo", DbType="Int")] System.Nullable<int> idUsuarioTipo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuarioTipo);
			return ((ISingleResult<LXCCSPS_LISTA_USUARIOSResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.LXCCSPS_CLIENTE_INFO")]
		public ISingleResult<LXCCSPS_CLIENTE_INFOResult> LXCCSPS_CLIENTE_INFO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cliente", DbType="NVarChar(45)")] string cliente)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cliente);
			return ((ISingleResult<LXCCSPS_CLIENTE_INFOResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.LXCCSPU_ALTA_ACT_CLIENTE")]
		public int LXCCSPU_ALTA_ACT_CLIENTE(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cliente", DbType="NVarChar(45)")] string cliente, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdEstado", DbType="BigInt")] System.Nullable<long> idEstado, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="BigInt")] System.Nullable<long> idUsuario, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="NVarChar(45)")] string nombre, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="APaterno", DbType="NVarChar(45)")] string aPaterno, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AMaterno", DbType="NVarChar(45)")] string aMaterno, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="RFC", DbType="NVarChar(45)")] string rFC, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Direccion", DbType="NVarChar(250)")] string direccion, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Municipio", DbType="NVarChar(45)")] string municipio, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CP", DbType="NVarChar(45)")] string cP, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TelefonoL", DbType="NVarChar(45)")] string telefonoL, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Extension", DbType="NVarChar(45)")] string extension, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TelefonoM", DbType="NVarChar(45)")] string telefonoM, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CorreoE", DbType="NVarChar(45)")] string correoE, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdServEstatus", DbType="BigInt")] System.Nullable<long> idServEstatus, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> idServicioTipo, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaContr", DbType="DateTime")] System.Nullable<System.DateTime> fechaContr, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaVenci", DbType="DateTime")] System.Nullable<System.DateTime> fechaVenci, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdContadorAsignado", DbType="BigInt")] System.Nullable<long> idContadorAsignado, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="NombreC1", DbType="NVarChar(45)")] string nombreC1, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="APaternoC1", DbType="NVarChar(45)")] string aPaternoC1, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AMaternoC1", DbType="NVarChar(45)")] string aMaternoC1, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TelefonoLC1", DbType="NVarChar(45)")] string telefonoLC1, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ExtensionC1", DbType="NVarChar(10)")] string extensionC1, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TelefonoMC1", DbType="NVarChar(45)")] string telefonoMC1, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CorreoEC1", DbType="NVarChar(45)")] string correoEC1, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="NombreC2", DbType="NVarChar(45)")] string nombreC2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="APaternoC2", DbType="NVarChar(45)")] string aPaternoC2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AMaternoC2", DbType="NVarChar(45)")] string aMaternoC2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TelefonoLC2", DbType="NVarChar(45)")] string telefonoLC2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ExtensionC2", DbType="NVarChar(10)")] string extensionC2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TelefonoMC2", DbType="NVarChar(45)")] string telefonoMC2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CorreoEC2", DbType="NVarChar(45)")] string correoEC2,


                    [global::System.Data.Linq.Mapping.ParameterAttribute(Name= "ServicioConta", DbType="Bit")] System.Nullable<bool> ServicioConta,
                    [global::System.Data.Linq.Mapping.ParameterAttribute(Name= "ServicioOD", DbType= "Bit")] System.Nullable<bool> ServicioOD,
                    [global::System.Data.Linq.Mapping.ParameterAttribute(Name= "IdComisionista", DbType="Int")] System.Nullable<long> IdComisionista,
                    [global::System.Data.Linq.Mapping.ParameterAttribute(Name= "IdNivel", DbType="Int")] System.Nullable<long> IdNivel,

                    [global::System.Data.Linq.Mapping.ParameterAttribute(Name= "CURP", DbType="NVarChar(50)")] string CURP,
                    [global::System.Data.Linq.Mapping.ParameterAttribute(Name = "NoExpediente", DbType = "NVarChar(50)")] string NoExpediente,






                    [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Resultado", DbType="Int")] ref System.Nullable<int> resultado)
		{

            IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cliente, idEstado, idUsuario, nombre, aPaterno, aMaterno, rFC, direccion, municipio, cP, telefonoL, extension, telefonoM, correoE, idServEstatus, idServicioTipo, fechaContr, fechaVenci, idContadorAsignado, nombreC1, aPaternoC1, aMaternoC1, telefonoLC1, extensionC1, telefonoMC1, correoEC1, nombreC2, aPaternoC2, aMaternoC2, telefonoLC2, extensionC2, telefonoMC2, correoEC2, ServicioConta, ServicioOD, IdComisionista, IdNivel, CURP, NoExpediente, resultado);
            //resultado = ((System.Nullable<int>)(result.GetParameterValue(33)));
            return ((int)(result.ReturnValue));
        }
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.LXCCSPS_CONTACTOS_AUT")]
		public ISingleResult<LXCCSPS_CONTACTOS_AUTResult> LXCCSPS_CONTACTOS_AUT([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdCliente", DbType="Int")] System.Nullable<int> idCliente)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idCliente);
			return ((ISingleResult<LXCCSPS_CONTACTOS_AUTResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.LXCCSPS_LISTADO_MOTIVO_LLAMADA")]
		public ISingleResult<LXCCSPS_LISTADO_MOTIVO_LLAMADAResult> LXCCSPS_LISTADO_MOTIVO_LLAMADA()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<LXCCSPS_LISTADO_MOTIVO_LLAMADAResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.LXCCSPI_CASO_NUEVO")]
		public int LXCCSPI_CASO_NUEVO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuarioCreacion", DbType="BigInt")] System.Nullable<long> idUsuarioCreacion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdCaso", DbType="BigInt")] ref System.Nullable<long> idCaso)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuarioCreacion, idCaso);
			idCaso = ((System.Nullable<long>)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.LXCCSPU_CASO_ACT")]
		public int LXCCSPU_CASO_ACT([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdCasoMotivo", DbType="BigInt")] System.Nullable<long> idCasoMotivo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdCliente", DbType="BigInt")] System.Nullable<long> idCliente, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuarioCreacion", DbType="BigInt")] System.Nullable<long> idUsuarioCreacion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="NVarChar(MAX)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdCaso", DbType="BigInt")] System.Nullable<long> idCaso, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Resultado", DbType="Int")] ref System.Nullable<int> resultado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idCasoMotivo, idCliente, idUsuarioCreacion, descripcion, idCaso, resultado);
			resultado = ((System.Nullable<int>)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.LXCCSPI_CREAR_MENSAJE")]
		public int LXCCSPI_CREAR_MENSAJE([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="BigInt")] System.Nullable<long> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdCliente", DbType="BigInt")] System.Nullable<long> idCliente, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdMensajeTipo", DbType="BigInt")] System.Nullable<long> idMensajeTipo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Mensaje", DbType="NVarChar(45)")] string mensaje, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Resultado", DbType="Int")] ref System.Nullable<int> resultado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuario, idCliente, idMensajeTipo, mensaje, resultado);
			resultado = ((System.Nullable<int>)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.LXCCSPS_LISTA_CLIENTE_ASIGNADOS")]
		public ISingleResult<LXCCSPS_LISTA_CLIENTE_ASIGNADOSResult> LXCCSPS_LISTA_CLIENTE_ASIGNADOS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="BigInt")] System.Nullable<long> idUsuario)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUsuario);
			return ((ISingleResult<LXCCSPS_LISTA_CLIENTE_ASIGNADOSResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.LXCCSPS_BUSCAR_CLIENTE")]
		public ISingleResult<LXCCSPS_BUSCAR_CLIENTEResult> LXCCSPS_BUSCAR_CLIENTE([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cliente", DbType="NVarChar(45)")] string cliente, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Rfc", DbType="NVarChar(45)")] string rfc, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="BigInt")] System.Nullable<long> idUsuario)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cliente, rfc, idUsuario);
			return ((ISingleResult<LXCCSPS_BUSCAR_CLIENTEResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.LXDECSPI_ALTA_DECLARACION")]
		public int LXDECSPI_ALTA_DECLARACION([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdCliente", DbType="BigInt")] System.Nullable<long> idCliente, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdPeriodo", DbType="BigInt")] System.Nullable<long> idPeriodo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdDeclaracionTipo", DbType="BigInt")] System.Nullable<long> idDeclaracionTipo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdDeclaracionEstado", DbType="BigInt")] System.Nullable<long> idDeclaracionEstado, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="BigInt")] System.Nullable<long> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AñoDeclaracion", DbType="NVarChar(10)")] string añoDeclaracion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LineaCaptura", DbType="NVarChar(250)")] string lineaCaptura, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumOperacion", DbType="NVarChar(45)")] string numOperacion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Monto", DbType="Money")] System.Nullable<decimal> monto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LlavePago", DbType="NVarChar(45)")] string llavePago, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaLimitePago", DbType="Date")] System.Nullable<System.DateTime> fechaLimitePago, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaPresentacion", DbType="Date")] System.Nullable<System.DateTime> fechaPresentacion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Resultado", DbType="Int")] ref System.Nullable<int> resultado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idCliente, idPeriodo, idDeclaracionTipo, idDeclaracionEstado, idUsuario, añoDeclaracion, lineaCaptura, numOperacion, monto, llavePago, fechaLimitePago, fechaPresentacion, resultado);
			resultado = ((System.Nullable<int>)(result.GetParameterValue(12)));
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Estado")]
	public partial class Estado : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _IdEstado;
		
		private string _Estado1;
		
		private System.DateTime _FechaCreacion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdEstadoChanging(long value);
    partial void OnIdEstadoChanged();
    partial void OnEstado1Changing(string value);
    partial void OnEstado1Changed();
    partial void OnFechaCreacionChanging(System.DateTime value);
    partial void OnFechaCreacionChanged();
    #endregion
		
		public Estado()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEstado", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long IdEstado
		{
			get
			{
				return this._IdEstado;
			}
			set
			{
				if ((this._IdEstado != value))
				{
					this.OnIdEstadoChanging(value);
					this.SendPropertyChanging();
					this._IdEstado = value;
					this.SendPropertyChanged("IdEstado");
					this.OnIdEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Estado", Storage="_Estado1", DbType="NVarChar(45) NOT NULL", CanBeNull=false)]
		public string Estado1
		{
			get
			{
				return this._Estado1;
			}
			set
			{
				if ((this._Estado1 != value))
				{
					this.OnEstado1Changing(value);
					this.SendPropertyChanging();
					this._Estado1 = value;
					this.SendPropertyChanged("Estado1");
					this.OnEstado1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaCreacion", DbType="DateTime NOT NULL")]
		public System.DateTime FechaCreacion
		{
			get
			{
				return this._FechaCreacion;
			}
			set
			{
				if ((this._FechaCreacion != value))
				{
					this.OnFechaCreacionChanging(value);
					this.SendPropertyChanging();
					this._FechaCreacion = value;
					this.SendPropertyChanged("FechaCreacion");
					this.OnFechaCreacionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ServicioStatus")]
	public partial class ServicioStatus : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _IdServicioStatus;
		
		private long _IdUsuarioCreacion;
		
		private string _ServicioStatus1;
		
		private System.DateTime _FechaCreacion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdServicioStatusChanging(long value);
    partial void OnIdServicioStatusChanged();
    partial void OnIdUsuarioCreacionChanging(long value);
    partial void OnIdUsuarioCreacionChanged();
    partial void OnServicioStatus1Changing(string value);
    partial void OnServicioStatus1Changed();
    partial void OnFechaCreacionChanging(System.DateTime value);
    partial void OnFechaCreacionChanged();
    #endregion
		
		public ServicioStatus()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdServicioStatus", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long IdServicioStatus
		{
			get
			{
				return this._IdServicioStatus;
			}
			set
			{
				if ((this._IdServicioStatus != value))
				{
					this.OnIdServicioStatusChanging(value);
					this.SendPropertyChanging();
					this._IdServicioStatus = value;
					this.SendPropertyChanged("IdServicioStatus");
					this.OnIdServicioStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuarioCreacion", DbType="BigInt NOT NULL")]
		public long IdUsuarioCreacion
		{
			get
			{
				return this._IdUsuarioCreacion;
			}
			set
			{
				if ((this._IdUsuarioCreacion != value))
				{
					this.OnIdUsuarioCreacionChanging(value);
					this.SendPropertyChanging();
					this._IdUsuarioCreacion = value;
					this.SendPropertyChanged("IdUsuarioCreacion");
					this.OnIdUsuarioCreacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="ServicioStatus", Storage="_ServicioStatus1", DbType="NVarChar(45) NOT NULL", CanBeNull=false)]
		public string ServicioStatus1
		{
			get
			{
				return this._ServicioStatus1;
			}
			set
			{
				if ((this._ServicioStatus1 != value))
				{
					this.OnServicioStatus1Changing(value);
					this.SendPropertyChanging();
					this._ServicioStatus1 = value;
					this.SendPropertyChanged("ServicioStatus1");
					this.OnServicioStatus1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaCreacion", DbType="DateTime NOT NULL")]
		public System.DateTime FechaCreacion
		{
			get
			{
				return this._FechaCreacion;
			}
			set
			{
				if ((this._FechaCreacion != value))
				{
					this.OnFechaCreacionChanging(value);
					this.SendPropertyChanging();
					this._FechaCreacion = value;
					this.SendPropertyChanged("FechaCreacion");
					this.OnFechaCreacionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ServicioTipo")]
	public partial class ServicioTipo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _IdServicioTipo;
		
		private long _IdUsuarioCreacion;
		
		private string _ServicioTipo1;
		
		private System.DateTime _FechaCreacion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdServicioTipoChanging(long value);
    partial void OnIdServicioTipoChanged();
    partial void OnIdUsuarioCreacionChanging(long value);
    partial void OnIdUsuarioCreacionChanged();
    partial void OnServicioTipo1Changing(string value);
    partial void OnServicioTipo1Changed();
    partial void OnFechaCreacionChanging(System.DateTime value);
    partial void OnFechaCreacionChanged();
    #endregion
		
		public ServicioTipo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdServicioTipo", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long IdServicioTipo
		{
			get
			{
				return this._IdServicioTipo;
			}
			set
			{
				if ((this._IdServicioTipo != value))
				{
					this.OnIdServicioTipoChanging(value);
					this.SendPropertyChanging();
					this._IdServicioTipo = value;
					this.SendPropertyChanged("IdServicioTipo");
					this.OnIdServicioTipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuarioCreacion", DbType="BigInt NOT NULL")]
		public long IdUsuarioCreacion
		{
			get
			{
				return this._IdUsuarioCreacion;
			}
			set
			{
				if ((this._IdUsuarioCreacion != value))
				{
					this.OnIdUsuarioCreacionChanging(value);
					this.SendPropertyChanging();
					this._IdUsuarioCreacion = value;
					this.SendPropertyChanged("IdUsuarioCreacion");
					this.OnIdUsuarioCreacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="ServicioTipo", Storage="_ServicioTipo1", DbType="NVarChar(45) NOT NULL", CanBeNull=false)]
		public string ServicioTipo1
		{
			get
			{
				return this._ServicioTipo1;
			}
			set
			{
				if ((this._ServicioTipo1 != value))
				{
					this.OnServicioTipo1Changing(value);
					this.SendPropertyChanging();
					this._ServicioTipo1 = value;
					this.SendPropertyChanged("ServicioTipo1");
					this.OnServicioTipo1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaCreacion", DbType="DateTime NOT NULL")]
		public System.DateTime FechaCreacion
		{
			get
			{
				return this._FechaCreacion;
			}
			set
			{
				if ((this._FechaCreacion != value))
				{
					this.OnFechaCreacionChanging(value);
					this.SendPropertyChanging();
					this._FechaCreacion = value;
					this.SendPropertyChanged("FechaCreacion");
					this.OnFechaCreacionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DeclaracionEstado")]
	public partial class DeclaracionEstado : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _IdDeclaracionEstado;
		
		private string _DeclaracionEstado1;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdDeclaracionEstadoChanging(long value);
    partial void OnIdDeclaracionEstadoChanged();
    partial void OnDeclaracionEstado1Changing(string value);
    partial void OnDeclaracionEstado1Changed();
    #endregion
		
		public DeclaracionEstado()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdDeclaracionEstado", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long IdDeclaracionEstado
		{
			get
			{
				return this._IdDeclaracionEstado;
			}
			set
			{
				if ((this._IdDeclaracionEstado != value))
				{
					this.OnIdDeclaracionEstadoChanging(value);
					this.SendPropertyChanging();
					this._IdDeclaracionEstado = value;
					this.SendPropertyChanged("IdDeclaracionEstado");
					this.OnIdDeclaracionEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="DeclaracionEstado", Storage="_DeclaracionEstado1", DbType="NVarChar(45) NOT NULL", CanBeNull=false)]
		public string DeclaracionEstado1
		{
			get
			{
				return this._DeclaracionEstado1;
			}
			set
			{
				if ((this._DeclaracionEstado1 != value))
				{
					this.OnDeclaracionEstado1Changing(value);
					this.SendPropertyChanging();
					this._DeclaracionEstado1 = value;
					this.SendPropertyChanged("DeclaracionEstado1");
					this.OnDeclaracionEstado1Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Periodo")]
	public partial class Periodo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _IdPeriodo;
		
		private string _Periodo1;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdPeriodoChanging(long value);
    partial void OnIdPeriodoChanged();
    partial void OnPeriodo1Changing(string value);
    partial void OnPeriodo1Changed();
    #endregion
		
		public Periodo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPeriodo", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long IdPeriodo
		{
			get
			{
				return this._IdPeriodo;
			}
			set
			{
				if ((this._IdPeriodo != value))
				{
					this.OnIdPeriodoChanging(value);
					this.SendPropertyChanging();
					this._IdPeriodo = value;
					this.SendPropertyChanged("IdPeriodo");
					this.OnIdPeriodoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Periodo", Storage="_Periodo1", DbType="NVarChar(45) NOT NULL", CanBeNull=false)]
		public string Periodo1
		{
			get
			{
				return this._Periodo1;
			}
			set
			{
				if ((this._Periodo1 != value))
				{
					this.OnPeriodo1Changing(value);
					this.SendPropertyChanging();
					this._Periodo1 = value;
					this.SendPropertyChanged("Periodo1");
					this.OnPeriodo1Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DeclaracionTipo")]
	public partial class DeclaracionTipo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _IdDeclaracionTipo;
		
		private string _DeclaracionTipo1;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdDeclaracionTipoChanging(long value);
    partial void OnIdDeclaracionTipoChanged();
    partial void OnDeclaracionTipo1Changing(string value);
    partial void OnDeclaracionTipo1Changed();
    #endregion
		
		public DeclaracionTipo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdDeclaracionTipo", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long IdDeclaracionTipo
		{
			get
			{
				return this._IdDeclaracionTipo;
			}
			set
			{
				if ((this._IdDeclaracionTipo != value))
				{
					this.OnIdDeclaracionTipoChanging(value);
					this.SendPropertyChanging();
					this._IdDeclaracionTipo = value;
					this.SendPropertyChanged("IdDeclaracionTipo");
					this.OnIdDeclaracionTipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="DeclaracionTipo", Storage="_DeclaracionTipo1", DbType="NVarChar(45) NOT NULL", CanBeNull=false)]
		public string DeclaracionTipo1
		{
			get
			{
				return this._DeclaracionTipo1;
			}
			set
			{
				if ((this._DeclaracionTipo1 != value))
				{
					this.OnDeclaracionTipo1Changing(value);
					this.SendPropertyChanging();
					this._DeclaracionTipo1 = value;
					this.SendPropertyChanged("DeclaracionTipo1");
					this.OnDeclaracionTipo1Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class LXCCSPS_VALIDAR_USUARIOResult
	{
		
		private long _IdUsuario;
		
		private long _IdUsuarioTipo;
		
		private string _Nombre;
		
		private string _APaterno;
		
		private string _AMaterno;
		
		public LXCCSPS_VALIDAR_USUARIOResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuario", DbType="BigInt NOT NULL")]
		public long IdUsuario
		{
			get
			{
				return this._IdUsuario;
			}
			set
			{
				if ((this._IdUsuario != value))
				{
					this._IdUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuarioTipo", DbType="BigInt NOT NULL")]
		public long IdUsuarioTipo
		{
			get
			{
				return this._IdUsuarioTipo;
			}
			set
			{
				if ((this._IdUsuarioTipo != value))
				{
					this._IdUsuarioTipo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(45) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APaterno", DbType="NVarChar(45) NOT NULL", CanBeNull=false)]
		public string APaterno
		{
			get
			{
				return this._APaterno;
			}
			set
			{
				if ((this._APaterno != value))
				{
					this._APaterno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AMaterno", DbType="NVarChar(45) NOT NULL", CanBeNull=false)]
		public string AMaterno
		{
			get
			{
				return this._AMaterno;
			}
			set
			{
				if ((this._AMaterno != value))
				{
					this._AMaterno = value;
				}
			}
		}
	}
	
	public partial class LXCCSPS_LISTA_USUARIOSResult
	{
		
		private long _IdUsuario;
		
		private long _IdUsuarioTipo;
		
		private string _Nombre;
		
		private string _APaterno;
		
		private string _AMaterno;
		
		public LXCCSPS_LISTA_USUARIOSResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuario", DbType="BigInt NOT NULL")]
		public long IdUsuario
		{
			get
			{
				return this._IdUsuario;
			}
			set
			{
				if ((this._IdUsuario != value))
				{
					this._IdUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuarioTipo", DbType="BigInt NOT NULL")]
		public long IdUsuarioTipo
		{
			get
			{
				return this._IdUsuarioTipo;
			}
			set
			{
				if ((this._IdUsuarioTipo != value))
				{
					this._IdUsuarioTipo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(45) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APaterno", DbType="NVarChar(45) NOT NULL", CanBeNull=false)]
		public string APaterno
		{
			get
			{
				return this._APaterno;
			}
			set
			{
				if ((this._APaterno != value))
				{
					this._APaterno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AMaterno", DbType="NVarChar(45) NOT NULL", CanBeNull=false)]
		public string AMaterno
		{
			get
			{
				return this._AMaterno;
			}
			set
			{
				if ((this._AMaterno != value))
				{
					this._AMaterno = value;
				}
			}
		}
	}
	
	public partial class LXCCSPS_CLIENTE_INFOResult
	{
		
		private string _Cliente;
		
		private bool _Activo;
		
		private string _RFC;
		
		private string _Nombre;
		
		private string _APaterno;
		
		private string _AMaterno;
		
		private string _Direccion;
		
		private string _Municipio;
		
		private long _IdEstado;
		
		private string _CodigoPostal;
		
		private string _NumeroLocal;
		
		private string _Extension;
		
		private string _NumeroMovil;
		
		private string _CorreoElectronico;
		
		private long _IdServicioTipo;
		
		private long _IdServicioStatus;
		
		private System.DateTime _FechaContratado;
		
		private System.DateTime _FechaVencimiento;
		
		private long _IdContadorAsignado;
		
		private long _IdCliente;


        private bool _ServicioConta;
        private bool _ServicioOD;
        private long _IdComisionista;
        private long _IdNivel;
        private string _Curp;
        private string _NoExpediente;


        public LXCCSPS_CLIENTE_INFOResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cliente", DbType="NVarChar(45) NOT NULL", CanBeNull=false)]
		public string Cliente
		{
			get
			{
				return this._Cliente;
			}
			set
			{
				if ((this._Cliente != value))
				{
					this._Cliente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Activo", DbType="Bit NOT NULL")]
		public bool Activo
		{
			get
			{
				return this._Activo;
			}
			set
			{
				if ((this._Activo != value))
				{
					this._Activo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RFC", DbType="NVarChar(45) NOT NULL", CanBeNull=false)]
		public string RFC
		{
			get
			{
				return this._RFC;
			}
			set
			{
				if ((this._RFC != value))
				{
					this._RFC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(45) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APaterno", DbType="NVarChar(45) NOT NULL", CanBeNull=false)]
		public string APaterno
		{
			get
			{
				return this._APaterno;
			}
			set
			{
				if ((this._APaterno != value))
				{
					this._APaterno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AMaterno", DbType="NVarChar(45) NOT NULL", CanBeNull=false)]
		public string AMaterno
		{
			get
			{
				return this._AMaterno;
			}
			set
			{
				if ((this._AMaterno != value))
				{
					this._AMaterno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this._Direccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Municipio", DbType="NVarChar(45) NOT NULL", CanBeNull=false)]
		public string Municipio
		{
			get
			{
				return this._Municipio;
			}
			set
			{
				if ((this._Municipio != value))
				{
					this._Municipio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEstado", DbType="BigInt NOT NULL")]
		public long IdEstado
		{
			get
			{
				return this._IdEstado;
			}
			set
			{
				if ((this._IdEstado != value))
				{
					this._IdEstado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoPostal", DbType="NVarChar(45) NOT NULL", CanBeNull=false)]
		public string CodigoPostal
		{
			get
			{
				return this._CodigoPostal;
			}
			set
			{
				if ((this._CodigoPostal != value))
				{
					this._CodigoPostal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroLocal", DbType="NVarChar(45) NOT NULL", CanBeNull=false)]
		public string NumeroLocal
		{
			get
			{
				return this._NumeroLocal;
			}
			set
			{
				if ((this._NumeroLocal != value))
				{
					this._NumeroLocal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Extension", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Extension
		{
			get
			{
				return this._Extension;
			}
			set
			{
				if ((this._Extension != value))
				{
					this._Extension = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroMovil", DbType="NVarChar(45) NOT NULL", CanBeNull=false)]
		public string NumeroMovil
		{
			get
			{
				return this._NumeroMovil;
			}
			set
			{
				if ((this._NumeroMovil != value))
				{
					this._NumeroMovil = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CorreoElectronico", DbType="NVarChar(45) NOT NULL", CanBeNull=false)]
		public string CorreoElectronico
		{
			get
			{
				return this._CorreoElectronico;
			}
			set
			{
				if ((this._CorreoElectronico != value))
				{
					this._CorreoElectronico = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdServicioTipo", DbType="BigInt NOT NULL")]
		public long IdServicioTipo
		{
			get
			{
				return this._IdServicioTipo;
			}
			set
			{
				if ((this._IdServicioTipo != value))
				{
					this._IdServicioTipo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdServicioStatus", DbType="BigInt NOT NULL")]
		public long IdServicioStatus
		{
			get
			{
				return this._IdServicioStatus;
			}
			set
			{
				if ((this._IdServicioStatus != value))
				{
					this._IdServicioStatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaContratado", DbType="Date NOT NULL")]
		public System.DateTime FechaContratado
		{
			get
			{
				return this._FechaContratado;
			}
			set
			{
				if ((this._FechaContratado != value))
				{
					this._FechaContratado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaVencimiento", DbType="Date NOT NULL")]
		public System.DateTime FechaVencimiento
		{
			get
			{
				return this._FechaVencimiento;
			}
			set
			{
				if ((this._FechaVencimiento != value))
				{
					this._FechaVencimiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdContadorAsignado", DbType="BigInt NOT NULL")]
		public long IdContadorAsignado
		{
			get
			{
				return this._IdContadorAsignado;
			}
			set
			{
				if ((this._IdContadorAsignado != value))
				{
					this._IdContadorAsignado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCliente", DbType="BigInt NOT NULL")]
		public long IdCliente
		{
			get
			{
				return this._IdCliente;
			}
			set
			{
				if ((this._IdCliente != value))
				{
					this._IdCliente = value;
				}
			}
		}



        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ServicioConta", DbType = "Bit NULL")]
        public bool ServicioConta
        {
            get
            {
                return this._ServicioConta;
            }
            set
            {
                if ((this._ServicioConta != value))
                {
                    this._ServicioConta = value;
                }
            }
        }



        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ServicioOD", DbType = "Bit NULL")]
        public bool ServicioOD
        {
            get
            {
                return this._ServicioOD;
            }
            set
            {
                if ((this._ServicioOD != value))
                {
                    this._ServicioOD = value;
                }
            }
        }


        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_IdComisionista", DbType = "Int NULL")]
        public long IdComisionista
        {
            get
            {
                return this._IdComisionista;
            }
            set
            {
                if ((this._IdComisionista != value))
                {
                    this._IdComisionista = value;
                }
            }
        }



        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_IdNivel", DbType = "Int NULL")]
        public long IdNivel
        {
            get
            {
                return this._IdNivel;
            }
            set
            {
                if ((this._IdNivel != value))
                {
                    this._IdNivel = value;
                }
            }
        }


        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Curp", DbType = "NVarChar(50) NULL", CanBeNull = true)]
        public string Curp
        {
            get
            {
                return this._Curp;
            }
            set
            {
                if ((this._Curp != value))
                {
                    this._Curp = value;
                }
            }
        }



        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_NoExpediente", DbType = "NVarChar(50) NULL", CanBeNull = true)]
        public string NoExpediente
        {
            get
            {
                return this._NoExpediente;
            }
            set
            {
                if ((this._NoExpediente != value))
                {
                    this._NoExpediente = value;
                }
            }
        }




    }
	
	public partial class LXCCSPS_CONTACTOS_AUTResult
	{
		
		private long _IdClienteContactoAut;
		
		private string _Nombre;
		
		private string _APaterno;
		
		private string _AMaterno;
		
		private string _TelefonoLocal;
		
		private string _Extension;
		
		private string _TelefonoMovil;
		
		private string _CorreoElectronico;
		
		public LXCCSPS_CONTACTOS_AUTResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdClienteContactoAut", DbType="BigInt NOT NULL")]
		public long IdClienteContactoAut
		{
			get
			{
				return this._IdClienteContactoAut;
			}
			set
			{
				if ((this._IdClienteContactoAut != value))
				{
					this._IdClienteContactoAut = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(45) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APaterno", DbType="NVarChar(45) NOT NULL", CanBeNull=false)]
		public string APaterno
		{
			get
			{
				return this._APaterno;
			}
			set
			{
				if ((this._APaterno != value))
				{
					this._APaterno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AMaterno", DbType="NVarChar(45) NOT NULL", CanBeNull=false)]
		public string AMaterno
		{
			get
			{
				return this._AMaterno;
			}
			set
			{
				if ((this._AMaterno != value))
				{
					this._AMaterno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelefonoLocal", DbType="NVarChar(45) NOT NULL", CanBeNull=false)]
		public string TelefonoLocal
		{
			get
			{
				return this._TelefonoLocal;
			}
			set
			{
				if ((this._TelefonoLocal != value))
				{
					this._TelefonoLocal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Extension", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Extension
		{
			get
			{
				return this._Extension;
			}
			set
			{
				if ((this._Extension != value))
				{
					this._Extension = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelefonoMovil", DbType="NVarChar(45) NOT NULL", CanBeNull=false)]
		public string TelefonoMovil
		{
			get
			{
				return this._TelefonoMovil;
			}
			set
			{
				if ((this._TelefonoMovil != value))
				{
					this._TelefonoMovil = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CorreoElectronico", DbType="NVarChar(45) NOT NULL", CanBeNull=false)]
		public string CorreoElectronico
		{
			get
			{
				return this._CorreoElectronico;
			}
			set
			{
				if ((this._CorreoElectronico != value))
				{
					this._CorreoElectronico = value;
				}
			}
		}
	}
	
	public partial class LXCCSPS_LISTADO_MOTIVO_LLAMADAResult
	{
		
		private long _IdCasoMotivo;
		
		private string _Motivo;
		
		public LXCCSPS_LISTADO_MOTIVO_LLAMADAResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCasoMotivo", DbType="BigInt NOT NULL")]
		public long IdCasoMotivo
		{
			get
			{
				return this._IdCasoMotivo;
			}
			set
			{
				if ((this._IdCasoMotivo != value))
				{
					this._IdCasoMotivo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Motivo", DbType="NVarChar(45) NOT NULL", CanBeNull=false)]
		public string Motivo
		{
			get
			{
				return this._Motivo;
			}
			set
			{
				if ((this._Motivo != value))
				{
					this._Motivo = value;
				}
			}
		}
	}
	
	public partial class LXCCSPS_LISTA_CLIENTE_ASIGNADOSResult
	{
		
		private string _CorreoElectronico;
		
		private string _NumeroMovil;
		
		public LXCCSPS_LISTA_CLIENTE_ASIGNADOSResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CorreoElectronico", DbType="NVarChar(45) NOT NULL", CanBeNull=false)]
		public string CorreoElectronico
		{
			get
			{
				return this._CorreoElectronico;
			}
			set
			{
				if ((this._CorreoElectronico != value))
				{
					this._CorreoElectronico = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroMovil", DbType="NVarChar(45) NOT NULL", CanBeNull=false)]
		public string NumeroMovil
		{
			get
			{
				return this._NumeroMovil;
			}
			set
			{
				if ((this._NumeroMovil != value))
				{
					this._NumeroMovil = value;
				}
			}
		}
	}
	
	public partial class LXCCSPS_BUSCAR_CLIENTEResult
	{
		
		private long _IdCliente;
		
		private long _IdClienteInformacion;
		
		private long _IdContadorAsignado;
		
		private string _Nombre;
		
		private string _APaterno;
		
		private string _AMaterno;
		
		private string _CorreoElectronico;
		
		private string _NumeroMovil;
		
		private bool _Activo;

        private bool _ServicioConta;
        private bool _ServicioOD;
        private long _IdComisionista;
        private long _IdNivel;
        private string _Curp;
        private string _NoExpediente;



        public LXCCSPS_BUSCAR_CLIENTEResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCliente", DbType="BigInt NOT NULL")]
		public long IdCliente
		{
			get
			{
				return this._IdCliente;
			}
			set
			{
				if ((this._IdCliente != value))
				{
					this._IdCliente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdClienteInformacion", DbType="BigInt NOT NULL")]
		public long IdClienteInformacion
		{
			get
			{
				return this._IdClienteInformacion;
			}
			set
			{
				if ((this._IdClienteInformacion != value))
				{
					this._IdClienteInformacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdContadorAsignado", DbType="BigInt NOT NULL")]
		public long IdContadorAsignado
		{
			get
			{
				return this._IdContadorAsignado;
			}
			set
			{
				if ((this._IdContadorAsignado != value))
				{
					this._IdContadorAsignado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(45) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APaterno", DbType="NVarChar(45) NOT NULL", CanBeNull=false)]
		public string APaterno
		{
			get
			{
				return this._APaterno;
			}
			set
			{
				if ((this._APaterno != value))
				{
					this._APaterno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AMaterno", DbType="NVarChar(45) NOT NULL", CanBeNull=false)]
		public string AMaterno
		{
			get
			{
				return this._AMaterno;
			}
			set
			{
				if ((this._AMaterno != value))
				{
					this._AMaterno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CorreoElectronico", DbType="NVarChar(45) NOT NULL", CanBeNull=false)]
		public string CorreoElectronico
		{
			get
			{
				return this._CorreoElectronico;
			}
			set
			{
				if ((this._CorreoElectronico != value))
				{
					this._CorreoElectronico = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroMovil", DbType="NVarChar(45) NOT NULL", CanBeNull=false)]
		public string NumeroMovil
		{
			get
			{
				return this._NumeroMovil;
			}
			set
			{
				if ((this._NumeroMovil != value))
				{
					this._NumeroMovil = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Activo", DbType="Bit NOT NULL")]
		public bool Activo
		{
			get
			{
				return this._Activo;
			}
			set
			{
				if ((this._Activo != value))
				{
					this._Activo = value;
				}
			}
		}


        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ServicioConta", DbType = "Bit NULL")]
        public bool ServicioConta
        {
            get
            {
                return this._ServicioConta;
            }
            set
            {
                if ((this._ServicioConta != value))
                {
                    this._ServicioConta = value;
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ServicioOD", DbType = "Bit NULL")]
        public bool ServicioOD
        {
            get
            {
                return this._ServicioOD;
            }
            set
            {
                if ((this._ServicioOD != value))
                {
                    this._ServicioOD = value;
                }
            }
        }


        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_IdComisionista", DbType = "Int NULL")]
        public long IdComisionista
        {
            get
            {
                return this._IdComisionista;
            }
            set
            {
                if ((this._IdComisionista != value))
                {
                    this._IdComisionista = value;
                }
            }
        }



        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_IdNivel", DbType = "Int NULL")]
        public long IdNivel
        {
            get
            {
                return this._IdNivel;
            }
            set
            {
                if ((this._IdNivel != value))
                {
                    this._IdNivel = value;
                }
            }
        }


        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_Curp", DbType = "NVarChar(50) NULL", CanBeNull = true)]
        public string Curp
        {
            get
            {
                return this._Curp;
            }
            set
            {
                if ((this._Curp != value))
                {
                    this._Curp = value;
                }
            }
        }


        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_NoExpediente", DbType = "NVarChar(50) NULL", CanBeNull = true)]
        public string NoExpediente
        {
            get
            {
                return this._NoExpediente;
            }
            set
            {
                if ((this._NoExpediente != value))
                {
                    this._NoExpediente = value;
                }
            }
        }

    }
}
#pragma warning restore 1591
